scss_files:
  - 'app/assets/stylesheets/**'
exclude:
  - 'app/assets/stylesheets/application.css'
  - 'vendor/assets/**'
linters:
  ImportantRule:
    enabled: false
  MergeableSelector:
    enabled: false
